### ISSUE TITLE
Request for Jade release

### ISSUE THREAD

**Issue by wjwwood** [ros-visualization/python_qt_binding#20]
This is blocking me from releasing `rviz` into Jade.

@dirk-thomas I haven't tried it yet, but you may need to consider merging https://github.com/ros-visualization/python_qt_binding/pull/15 for Utopic+.

**Comment by dirk-thomas** [comment]
Done: ros/rosdistro#8112

Ubuntu (I tried only Vivid) is not affected by #13.
