### ISSUE TITLE
cmake/sip_configure.py calls non standard 'qmake-qt4'

### ISSUE THREAD

**Issue by aballier** [ros-visualization/python_qt_binding#22]
python_qt_binding has been fixed for recent pyqt versions, thanks for that, however it has been done in a way that calls 'qmake-qt4' (instead of just 'qmake') which seems to be an invention of some distributions ( seen e.g. on https://wiki.archlinux.org/index.php/Qt#Installation and https://wiki.archlinux.org/index.php/Qt#Default_Qt_toolkit ) and that I don't have.

I am not sure how this should be fixed, archlinux wiki mentions a QT_SELECT environment variable, so maybe just calling 'qmake' with this variable set would work.

**Comment by dirk-thomas** [comment]
Since this seems to be specific to whatever system you are using (and I have no way to check / confirm this) can you please try your proposed change and report back if it works?

Providing a PR for hit would be highly appreciated and likely speed up the process :wink:

**Comment by aballier** [comment]
I'm already patching it locally to replace 'qmake-qt4' with 'qmake' and it seems to work perfectly. What I'm not sure is if this doesn't break other systems :/

**Comment by dirk-thomas** [comment]
Related to a recent change: #13

On ubuntu the dependency `qt4-qmake` depends on `qtchooser` which will bring in `qmake`. So it should be fine on Ubuntu. I have created PR #23 to address it.

@bchretien Can you please double check that it still works for you with the PR applied?

**Comment by bchretien** [comment]
```sh
$ qmake -v
QMake version 3.0
Using Qt version 5.4.1 in /usr/lib
$ QT_SELECT=4 qmake -v
QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib
```

Looks good to me.

**Comment by dirk-thomas** [comment]
@bchretien Thank you for checking.
