### ISSUE TITLE
Update PyPI

### ISSUE THREAD

**Issue by vidartf** [ros-visualization/python_qt_binding#26]
Currently `python_qt_binding` is only at [0.2.14 on PyPI](https://pypi.python.org/pypi/python_qt_binding), meaning python3 Qt apps cannot have it as an automatically installed dependency when installing from pip. Would it be possible to update the package version available on PyPI to fix this?

**Comment by dirk-thomas** [comment]
Sure, I have just uploaded the current release (0.2.17) to PyPI.
