### ISSUE TITLE
Support for Qt5

### ISSUE THREAD

**Issue by wjwwood** [ros-visualization/python_qt_binding#29]
This is a dependency of rviz, @dirk-thomas do you think that any changes will be necessary here for the Qt5 migration? Currently the only issue is that it has a dependency on `python-qt-bindings` and `qt4-qmake` which would need to change on a Kinetic branch.

**Comment by dirk-thomas** [comment]
The `qt5` branch already uses Qt5 dependencies in the manifest: https://github.com/ros-visualization/python_qt_binding/blob/781dc870e9a3ad7eb5376a8d80ecb54058fb63d4/package.xml#L30-L33

Beyond the changes already on that branch more work is necessary for PySide(2).

**Comment by wjwwood** [comment]
I think we're tracking this well enough elsewhere, I'm going to close this.
