### ISSUE TITLE
Can install ros-kinetic-python-qt-binding

### ISSUE THREAD

**Issue by facontidavide** [ros-visualization/python_qt_binding#39]
Hi,

I have Ubuntu 16.04 64 bits and I am tryin to install ros-kinetic-python-qt-binding.
Unfortunately I get this error:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-kinetic-python-qt-binding : Depends: libpyside2-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

Note that __libpyside2-dev__ is installed

```
➜ sudo apt-get install -f libpyside2-dev      
         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpyside2-dev is already the newest version (2.0.0+dev-0~201604151742~rev1858~pkg38~ubuntu16.04.1).
```

**Comment by dirk-thomas** [comment]
The packages install fine for me as well as on the build farm. Therefore I don't think it is a problem with the packages itself but related to your system state.

You might want to ask the question on answers.ros.org (and try to search for similar questions before) to get feedback from a bigger audience.

**Comment by tfoote** [comment]
`E: Unable to correct problems, you have held broken packages.` indicates that you have broken apt packages on your system. You need to resolve that before most apt based operations will work. 

Here are a few resources that may help you.
https://www.linuxquestions.org/questions/linux-desktop-74/unable-to-correct-problems-you-have-held-broken-packages-4175510237/
https://www.linuxquestions.org/questions/debian-26/e-unable-to-correct-problems-you-have-held-broken-packages-4175490139/
