### ISSUE TITLE
Using CMake extras in non-ROS project

### ISSUE THREAD

**Issue by machinekoder** [ros-visualization/python_qt_binding#50]
Is it possible to use the CMake package provided by `python_qt_binding` in other non-ROS projects?

**Comment by machinekoder** [comment]
Then the question is how. It looks like `catkin` generates a `python_qt_bindingConfig.cmake` from the source of this project.

**Comment by dirk-thomas** [comment]
I am not sure I understand your question.

> It looks like `catkin` generates a `python_qt_bindingConfig.cmake` from the source of this project.

Yes, that enables you to `find_package(python_qt_binding)` from any other CMake file.

**Comment by dirk-thomas** [comment]
I am not sure if my previous comments have answered your question but I will go ahead and close this ticket for now due to no further response. Please feel free to continue commenting.
