### ISSUE TITLE
Failed to process package 'python_qt_binding'

### ISSUE THREAD

**Issue by rafiq-rana** [ros-visualization/python_qt_binding#62]
CMake Error at /opt/ros/melodic/share/catkin/cmake/assert.cmake:17 (message):
  

  Assertion failed: check for file existence, but filename
  (RT_LIBRARY-NOTFOUND) unset.  Message: RT Library

Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/tools/rt.cmake:42 (assert_file_exists)
  /opt/ros/melodic/share/catkin/cmake/all.cmake:163 (include)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pi/ros_catkin_ws/build_isolated/python_qt_binding/CMakeFiles/CMakeOutput.log".
See also "/home/pi/ros_catkin_ws/build_isolated/python_qt_binding/CMakeFiles/CMakeError.log".
<== Failed to process package 'python_qt_binding': 
  Command '['/opt/ros/melodic/env.sh', 'cmake', '/home/pi/ros_catkin_ws/src/python_qt_binding', '-DCATKIN_DEVEL_PREFIX=/home/pi/ros_catkin_ws/devel_isolated/python_qt_binding', '-DCMAKE_INSTALL_PREFIX=/opt/ros/melodic', '-DCMAKE_BUILD_TYPE=Release', '-G', 'Unix Makefiles']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/pi/ros_catkin_ws/build_isolated/python_qt_binding && /opt/ros/melodic/env.sh cmake /home/pi/ros_catkin_ws/src/python_qt_binding -DCATKIN_DEVEL_PREFIX=/home/pi/ros_catkin_ws/devel_isolated/python_qt_binding -DCMAKE_INSTALL_PREFIX=/opt/ros/melodic -DCMAKE_BUILD_TYPE=Release -G 'Unix Makefiles'

Command failed, exiting.

**Comment by dirk-thomas** [comment]
Please provide more information like the platform, version, what version of the repo are you trying to build, exact steps / commands being invoked...

**Comment by dirk-thomas** [comment]
Closing due to no response.
