### ISSUE TITLE
PyQT5 requires Python 3.4 or above, why is PyQt5 a requirements?

### ISSUE THREAD

**Issue by ashishk88** [ros-visualization/python_qt_binding#63]
https://github.com/ros-visualization/python_qt_binding/blob/0c4250629f8b02ca80f710628c6110714f182a22/cmake/sip_configure.py#L9

**Comment by dirk-thomas** [comment]
ROS 1 Kinetic and newer as well as ROS 2 target Qt 5: see [REP 3](http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021). Therefore in those distributions `PyQt5` is being used.

> PyQT5 requires Python 3.4 or above

Why do you think that is the case? ROS 1 uses Python 2 and works just fine with PyQt 5.

**Comment by dirk-thomas** [comment]
Closing due to no response.
