### ISSUE TITLE
Accident string concatenation

### ISSUE THREAD

**Issue by danielwangksu** [ros-visualization/python_qt_binding#65]
https://github.com/ros-visualization/python_qt_binding/blob/0c4250629f8b02ca80f710628c6110714f182a22/src/python_qt_binding/binding_helper.py#L85-L87

**Comment by dirk-thomas** [comment]
Thank you for reporting the problem. Please consider taking the time to create a pull request for it - especially if the patch is that trivial.

**Comment by danielwangksu** [comment]
Sure @dirk-thomas
