### ISSUE TITLE
cmake file from new version of shiboken2 does not set `SHIBOKEN_BINARY` any more

### ISSUE THREAD

**Issue by MikeChou** [ros-visualization/python_qt_binding#69]
At least for `shiboken2` v5.13.0, cmake file set target `Shiboken2::shiboken2`, not variable `SHIBOKEN_BINARY` any more.

In `shiboken_helper.cmake`, we should detect and then choose to use `${SHIBOKEN_BINARY}` or `Shiboken2::shiboken2` correspondingly.

Workaround for users with this issue: change `${SHIBOKEN_BINARY}` to `Shiboken2::shiboken2` in `shiboken_helper.cmake`.

**Comment by dirk-thomas** [comment]
Please consider to contribute a pull request to address this.

**Comment by no-preserve-root** [comment]
@dirk-thomas Is the MR #77 okay? It should fix the issue and be compatible with older Shiboken versions.
