### ISSUE TITLE
New release for melodic

### ISSUE THREAD

**Issue by simonschmeisser** [ros-visualization/python_qt_binding#72]
I just switched to Qt 5.12.4 on my test system and noticed that I need the current version from git to compile rviz due to #64 Could we have a new release soon for convenience?

thanks!

**Comment by dirk-thomas** [comment]
A release for which ROS  distribution?

**Comment by simonschmeisser** [comment]
ah sorry mixed up Ubuntu and ROS code names ... I was talking about melodic

**Comment by dirk-thomas** [comment]
Done in ros/rosdistro#22454.
