### ISSUE TITLE
PySide2 uses CMake target instead of variable

### ISSUE THREAD

**Issue by stertingen** [ros-visualization/python_qt_binding#78]
On Arch linux (PySide2 version 5.13.2), the variables `PYSIDE_LIBRARY` and `PYSIDE_INCLUDE_DIR` are not set, which leads to build failures like https://github.com/ros-visualization/qt_gui_core/issues/142.

Setting `PYSIDE_INCLUDE_DIR` as CMake argument is a workaround, but not a clean solution.

A proper fix could look like https://github.com/FreeCAD/FreeCAD/commit/3939e4543ef4be6c50581d9bff77e930fb1d9d03.

**Comment by dirk-thomas** [comment]
Please consider to contribute a pull request to address this in a backwards compatible way.
