### ISSUE TITLE
python_qt_binding Noetic Release?

### ISSUE THREAD

**Issue by sloretz** [ros-visualization/python_qt_binding#82]
Mind releasing this repo into Noetic? It looks like all dependencies have been released. It looks like 175 other repos need `python_qt_binding` to be released.

http://repositories.ros.org/status_page/blocked_releases_noetic.html?q=id%3D%22python_qt_binding%22&s=6&r=1

**Comment by awesomebytes** [comment]
If we could re-release also on kinetic, that would be great.

Currently needing on Gentoo something over 0.3.4 to get this `-l-lpthread` fix: https://github.com/ros-visualization/python_qt_binding/commit/0a4893791039d5c3f851ee7bc2de832209d52f6d

**Comment by dirk-thomas** [comment]
On Feb 18th the necessary dependencies have been updated from Python 3.7 to Python 3.8. These updated debs are now available so I will look into making a Noetic release soon.

**Comment by dirk-thomas** [comment]
@awesomebytes Even though off topic: 0.3.7 has been released into Kinetic.

**Comment by dirk-thomas** [comment]
Done: ros/rosdistro#23906.

**Comment by awesomebytes** [comment]
@dirk-thomas Thank you very much :)
